export const productTypes = {
  GET_ALL_PRODUCT : 'GET_ALL_PRODUCT',
  ADD_PRODUCT: 'ADD_PRODUCT',
  DELETE_PRODUCT : 'DELETE_PRODUCT',
 }
 
export const snackBarTypes = {
    SNACKBAR_STATE : 'SNACKBAR_STATE',
    SNACKBAR_MESSAGE :'SNACKBAR_MESSAGE'
}

export const basketTypes = {
  CHANGE_QUANTITY: 'CHANGE_QUANTITY',
  DELETE_ITEM:'DELETE_ITEM'
}