export const productTypes = {
  GET_ALL_PRODUCT : 'GET_ALL_PRODUCT',
  ADD_PRODUCT: 'ADD_PRODUCT',
  DELETE_PRODUCT : 'DELETE_PRODUCT',

  EDIT_PRODUCT: 'EDIT_PRODUCT',
  ADD_IMAGES_PRODUCT : 'ADD_IMAGES_PRODUCT',
  DELETE__ONE_IMAGE_PRODUCT : 'DELETE__ONE_IMAGE_PRODUCT',

  GET_ALL_SEARCHPRODUCT: 'GET_ALL_SEARCHPRODUCT',
  GET_ALL_RATING: 'GET_ALL_RATING',
  CHANGE_RATING: 'CHANGE_RATING',
  GET_ONE_PRODUCT : 'GET_ONE_PRODUCT',
  GET_ALL_TYPES : 'GET_ALL_TYPES',
 }
 
export const snackBarTypes = {
    SNACKBAR_STATE : 'SNACKBAR_STATE',
    SNACKBAR_MESSAGE :'SNACKBAR_MESSAGE'
}
export const authTypes = {
  AUTH_LOG : 'AUTH_LOG',
  AUTH_USERDATA : 'AUTH_USERDATA',
  AUTH_ERRORMESSAGE : 'AUTH_ERRORMESSAGE',
  AUTH_ADMIN : 'AUTH_ADMIN',
}

export const basketTypes = {
  ADD_TO_BASKET: 'ADD_TO_BASKET',
  CHANGE_QUANTITY: 'CHANGE_QUANTITY',
  
  DELETE_ITEM:'DELETE_ITEM',
  BASKET_FROM_LOCAL: 'BASKET_FROM_LOCAL',
}

export const commentTypes = {
  ADD_ONE_COMMENT: 'ADD_ONE_COMMENT',
  SET_ALL_COMMENT_ONE_PRODUCT: 'SET_ALL_COMMENT_ONE_PRODUCT',
}
