export const productTypes = {
  GET_ALL_PRODUCT : 'GET_ALL_PRODUCT',
  ADD_PRODUCT: 'ADD_PRODUCT',
  DELETE_PRODUCT : 'DELETE_PRODUCT',
  GET_ONE_PRODUCT : 'GET_ONE_PRODUCT',
 }
 
export const snackBarTypes = {
    SNACKBAR_STATE : 'SNACKBAR_STATE',
    SNACKBAR_MESSAGE :'SNACKBAR_MESSAGE'
}
export const authTypes = {
    AUTH_LOG : 'AUTH_LOG',
    AUTH_USERDATA : 'AUTH_USERDATA',
    AUTH_ERRORMESSAGE : 'AUTH_ERRORMESSAGE',
 }
export const basketTypes = {
  CHANGE_QUANTITY: 'CHANGE_QUANTITY',
  DELETE_ITEM:'DELETE_ITEM'
}