/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Viggo (https://sketchfab.com/Viggoa)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/high-poly-sofa-7ef0d9d98ec0437bbbfe352ed9e0e707
title: High Poly Sofa
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

function Model(props) {
  const { nodes, materials } = useGLTF('/3dfurniture/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1.64}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cube_Material004_0.geometry} material={materials['Material.004']} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cube001_Material004_0.geometry} material={materials['Material.004']} />
            <mesh geometry={nodes.Cube001_Material004_0_1.geometry} material={materials['Material.004']} />
          </group>
          <group position={[0, -16.2, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cube002_Material004_0.geometry} material={materials['Material.004']} />
          </group>
          <group position={[0, -79.38, -17.66]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cube003_Material004_0.geometry} material={materials['Material.004']} />
          </group>
          <group position={[0, 0, -7.91]} rotation={[-Math.PI / 2, 0, 0]} scale={[103.93, 100, 100]}>
            <mesh geometry={nodes.Cube004_Material004_0.geometry} material={materials['Material.004']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')

export default Model